### ISSUE TITLE
Create an homebrew release for bomctl

### ISSUE THREAD

**Issue by idunbarh** [bomctl/bomctl#35]
We should be releasing bomctl in homebrew.

It looks like this can be done from [goreleaser](https://goreleaser.com/customization/homebrew/).

**Comment by jhoward-lm** [comment]
- Make sure `bomctl-goreleaser-bot` github app is installed to the `homebrew-bomctl` repository
- In .github/workflows/goreleaser.yml, need to add a step before the `Run GoReleaser` step that looks like
  ```yaml
        - name: Get GitHub App installation token
          uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1.9.3
          id: app-token
          with:
            app-id: ${{ vars.GORELEASER_BOT_APP_ID }}
            private-key: ${{ secrets.GORELEASER_BOT_RSA_PRIVATE_KEY }}
            owner: bomctl
            repositories: homebrew-bomctl
  ```
- Add the token as an environment variable to the `Run GoReleaser` step
  ```yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
  ```
- Reference the `HOMEBREW_TAP_GITHUB_TOKEN` environment variable inside the `brews:` section of `.goreleaser.yml`
